apiVersion: v1
kind: Service
metadata:
  labels:
    app: jekyll
  name: jekyll
spec:
  ports:
  - name: 4000-tcp
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: jekyll
    deploymentconfig: jekyll
  sessionAffinity: None
  type: ClusterIP
